name: Terraform Execution

on:
  workflow_run:
    workflows: ["Build WordPress Docker Image and push it to docker"]
    types:
      - completed
#on:
 # push:
  #  branches:
   #   - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Update to the desired Terraform version

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Apply
      run: terraform apply -auto-approve
